apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
       app: app
  template:
    metadata:
      labels:
        app: app
        visualize: "true"
    spec:
      containers:
      - name: app
        image: subhiksha610/app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: app
spec:
  selector:
    app: app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP